### ISSUE TITLE
Python/Selenium Compatability

### ISSUE THREAD

**Issue by asherppan** [0x676e67/fs#15]
How would I use this with python selenium? Also, is this project/api_key free? I saw there were 2 types of requests?

**Comment by gngpp** [comment]
It’s completely free. This API key is set by yourself to prevent the interface from being abused by others.

**Comment by asherppan** [comment]
But is this compatible with python selenium?

**Comment by asherppan** [comment]
Also, how would you get the image for the captcha that is used in the request?

**Comment by asherppan** [comment]
What I'm trying to get to is using this in python, as I don't know how to make the tutorial compatible in python.

**Comment by gngpp** [comment]
I can't help you because that's not what this project is capable of.  You need the program to process the funcaptcha picture download yourself, then use this program to identify it and then submit the answer to pass the challenge.

**Comment by sachinsenal0x64** [comment]
@gngpp I agree that this is not related to selenium.

**Comment by asherppan** [comment]
> I can't help you because that's not what this project is capable of. You need the program to process the funcaptcha picture download yourself, then use this program to identify it and then submit the answer to pass the challenge.

How would you use this? I don't understand the installation guide. Where do I run the commands?

**Comment by Foolian2** [comment]
> I can't help you because that's not what this project is capable of. You need the program to process the funcaptcha picture download yourself, then use this program to identify it and then submit the answer to pass the challenge.

correct me if im wrong, but how i understand it i have to give the type of captcha as request not the blob itself like as given on capsolver?

**Comment by 0x676e67** [comment]
> > I can't help you because that's not what this project is capable of. You need the program to process the funcaptcha picture download yourself, then use this program to identify it and then submit the answer to pass the challenge.我无法帮助你，因为这不是这个项目的能力。您需要程序自行处理下载的funcaptcha图片，然后使用该程序对其进行识别，然后提交答案以通过挑战。
> 
> correct me if im wrong, but how i understand it i have to give the type of captcha as request not the blob itself like as given on capsolver?如果我错了，请纠正我，但我如何理解它，我必须根据请求提供验证码类型，而不是像 capsolver 上给出的那样提供 Blob 本身？

Yes, this is just a service that processes image recognition. How to submit the remaining verification code is not within the scope of this project.
